# Generated by Django 4.2 on 2023-05-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='default_password', max_length=128),
            preserve_default=False,
        ),
    ]
